### ISSUE TITLE
A small configuration to Info.plist is needed.

### ISSUE THREAD

**Issue by sbd2015** [magnatronus/flutter-devicelocale#1]
I had an issue that current locale always returns English for language code.
And I found out I need a small editing to Info.plist as [the link](https://github.com/flutter/flutter/issues/14128#issuecomment-401028142) says.
I'm aware that the issue is not coming from the plugin, but I think it would be helpful if it's noted for users.

**Comment by amendgit** [comment]
I helps, thanks.
