### ISSUE TITLE
Failed to build application in Iphone XR 12.3.1

### ISSUE THREAD

**Issue by humanolaranja** [magnatronus/flutter-devicelocale#11]
I'm facing a issue when I do `flutter run` in an Iphone XR 12.3.1

This is the output

```
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Non-fat binary /Users/user/Documents/project/admin/build/ios/Debug-iphoneos/Runner.app/Frameworks/devicelocale.framework/devicelocale is not
    armv7. Running lipo -info:
    Non-fat file: /Users/user/Documents/project/admin/build/ios/Debug-iphoneos/Runner.app/Frameworks/devicelocale.framework/devicelocale is
    architecture: arm64
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description
Could not build the precompiled application for the device.
Error launching application on Iphone XR 12.3.1
```

It's everything working well with simulator, and with all this apple devices too.
- IPod touch 6a gen 12.4.5
- Iphone 8 12.3.1
- IPad 12.0.1

I tried to build with xcode, worked too.

Flutter Doctor
**Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76,
  locale pt-BR)**

**Comment by magnatronus** [comment]
Not sure, have you tried running 

```
flutter clean
```

first.

From your error I don't think it is an issue with the plugin . I note that you are not running the latest(stable) version of Flutter (it says **Channel unknown**). Maybe try changing to the latest stable release of `flutter.
