### ISSUE TITLE
Device’s primary locale may not contain country code

### ISSUE THREAD

**Issue by denis-evteev** [magnatronus/flutter-devicelocale#12]
Hi there,

First of all, thanks for your plugin.

It looks like in your iOS implementation you’re using a `%@-%@` template for stringifying the device’s primary locale. Nonetheless, the locale may not always contain a country code, in which case a `(null)` text is inserted in the second placeholder.

For example, for the English language (which corresponds to the `en` locale), the plugin’s `currentLocale()` call returns the `en-(null)` string.

Could you please fix this — probably won’t take you long. Thanks!

**Comment by degloff** [comment]
Hi I have the same problem on iOS. Here is an example:

If I choose the region to be US

```
  List languages = await Devicelocale.preferredLanguages;
  String locale = await Devicelocale.currentLocale;
  print('current locale: $locale, preferred device languages:');
  languages.forEach((l) => print(l));
```

produces the following output: 

```
flutter: current locale: en-US, preferred device languages:
flutter: en-US
flutter: th-US
flutter: vi-US
flutter: en-GB
flutter: zh-Hant-US
flutter: zh-Hans-US
flutter: de-US
flutter: de-AT
```

If I change the region to say Germany (DE) then I have -DE appended but this is wrong. The iOS region should not be there.

**Comment by magnatronus** [comment]
> Hi there,
> 
> First of all, thanks for your plugin.
> 
> It looks like in your iOS implementation you’re using a `%@-%@` template for stringifying the device’s primary locale. Nonetheless, the locale may not always contain a country code, in which case a `(null)` text is inserted in the second placeholder.
> 
> For example, for the English language (which corresponds to the `en` locale), the plugin’s `currentLocale()` call returns the `en-(null)` string.
> 
> Could you please fix this — probably won’t take you long. Thanks!

 @denis-evteev  Hi, a new version of the plugin 0.2.2. now does not return the locale on iOs if it is null.
I am curious how you managed to get the locale as (null). as no matter what I do I could not get this to happen. It would be great if you had a step - by - step as I would like to test this situation.

Thanks for the feedback

**Comment by magnatronus** [comment]
> Hi I have the same problem on iOS. Here is an example:
> 
> If I choose the region to be US
> 
> ```
>   List languages = await Devicelocale.preferredLanguages;
>   String locale = await Devicelocale.currentLocale;
>   print('current locale: $locale, preferred device languages:');
>   languages.forEach((l) => print(l));
> ```
> 
> produces the following output:
> 
> ```
> flutter: current locale: en-US, preferred device languages:
> flutter: en-US
> flutter: th-US
> flutter: vi-US
> flutter: en-GB
> flutter: zh-Hant-US
> flutter: zh-Hans-US
> flutter: de-US
> flutter: de-AT
> ```
> 
> If I change the region to say Germany (DE) then I have -DE appended but this is wrong. The iOS region should not be there.

@degloff   Could you explain more as I am not sure why you say that -DE should not be appended. The plugin os only returning the value that it detects as the locale and returns what it finds, which looks like in this case it should be -DE .

**Comment by denis-evteev** [comment]
Thanks for fixing this!

> I am curious how you managed to get the locale as (null). as no matter what I do I could not get this to happen. It would be great if you had a step - by - step as I would like to test this situation.

You can test this in a simulator — just select a language with no text in parentheses, meaning there’s no country code for that language (e.g. English, French or German):
![image](https://user-images.githubusercontent.com/3929460/76685280-7f120f80-6623-11ea-970e-83adc462bed7.png)
