### ISSUE TITLE
Add Android embedding v2 support

### ISSUE THREAD

**Issue by denis-evteev** [magnatronus/flutter-devicelocale#17]
Hi, any chance of adding the [Android embedding v2 support](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration)?

**Comment by magnatronus** [comment]
Hi, I will take a look, but cannot give any time scales currently. thank you for the request.

**Comment by magnatronus** [comment]
@denis-evteev  The plug-in should now be at 0.3.0 which has been updated for Android Embedding V2

**Comment by denis-evteev** [comment]
Awesome, thanks!
