### ISSUE TITLE
Feature Request - Current locale return value

### ISSUE THREAD

**Issue by michael-ottink** [magnatronus/flutter-devicelocale#19]
Could you return a Locale object with the properties country code and language instead of a String us_US?

**Comment by magnatronus** [comment]
Hi thanks for the suggestion, I can take a look  but at the moment I cannot give any estimate on time scales.

For now could you not do the following (assuming you have the locale as a string - "us_US")

String localeAsString = "us_US" 
List localeList = localAsString.split("_");
Locale locale = Locale( localeList[0], localeList[1]);

This is probably part of the update I would add.

**Comment by michael-ottink** [comment]
Hey! Yes I did that. But for the future I think returning a locale might be better.

**Comment by magnatronus** [comment]
OK I will add this in the next time, probably as a separate method, possibly   **.asLocale** or similar.

**Comment by magnatronus** [comment]
@michael-ottink  - I have now added 2 new methods. (V0.3.1) that should return Locale objects rather than Strings
