### ISSUE TITLE
NoSuchMethodError on android

### ISSUE THREAD

**Issue by huzhiren** [magnatronus/flutter-devicelocale#2]
E/flutter (18177): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: No virtual method getLocales()Landroid/os/LocaleList; in class Landroid/content/res/Configuration; or its super classes (declaration of 'android.content.res.Configuration' appears in /system/framework/framework.jar)
E/flutter (18177):      at com.example.devicelocale.DevicelocalePlugin.getPreferredLanguages(DevicelocalePlugin.java:36)
E/flutter (18177):      at com.example.devicelocale.DevicelocalePlugin.onMethodCall(DevicelocalePlugin.java:24)
E/flutter (18177):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter (18177):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter (18177):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/flutter (18177):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (18177):      at android.os.MessageQueue.next(MessageQueue.java:148)
E/flutter (18177):      at android.os.Looper.loop(Looper.java:151)      
E/flutter (18177):      at android.app.ActivityThread.main(ActivityThread.java:5931)
E/flutter (18177):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (18177):      at java.lang.reflect.Method.invoke(Method.java:372)
E/flutter (18177):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
E/flutter (18177):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by magnatronus** [comment]
Hi, could you expand on how this error occurred and if you were running on device or sim, with Platform, Android version, Flutter version etc.

And I will try and replicate.

Thanks.

**Comment by huzhiren** [comment]
It is a real device, model: Huawei Y5 II CUN-L02
But I think it is related to the Android API 23, which doesn't have such API,  can we have an alternative method, like in my fork repo?

**Comment by magnatronus** [comment]
OK let me take a look at your repo

**Comment by magnatronus** [comment]
The getLocales() method was first put in the API 24(Android 7), so you are correct that API 23 does not have this call.   I will try an update this when I have some time, thanks for the feedback.

**Comment by magnatronus** [comment]
I have updated and published a new version (0.2.0) which should hopefully fix the issue you were having.
