### ISSUE TITLE
currentLocale & currentAsLocale always return `en-US`

### ISSUE THREAD

**Issue by MoustafaMesbah** [magnatronus/flutter-devicelocale#22]
flutter version 1.17.5
dart version 2.8.4
iOS 13.6 iPhone 11 pro

FYI: `Devicelocale.preferredLanguages [0]` return the correct current locale 

----
update:
`currentLocale` is NOT equal `preferredLanguages [0]`
I tested it on Simulator, I will test it on a real device and post another update!

----
update:
I tested it on a real device and the behaviour is the same, `currentLocale` always return `en` as current language regardless it is the current language or not

**Comment by Tienisto** [comment]
Are you sure, you set up everything correctly?
Because I also encountered that problem, you have to add this into the `ios/Runner/Info.plist` somewhere in the file:
```
<key>CFBundleLocalizations</key>
<array>
   <string>en</string>
   <string>de</string>
</array>
```

**Comment by magnatronus** [comment]
@Tienisto is correct unless you define the languages available to iOS in the Info.plist they will not be available. See [CFBundleLocalizations](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-109552). for more info

**Comment by Tienisto** [comment]
@magnatronus I think you misunderstood me, it is working fine on my side.

**Comment by MoustafaMesbah** [comment]
After adding the locales codes to ios/Runner/Info.plist as @Tienisto mentioned in his [comment](https://github.com/magnatronus/flutter-devicelocale/issues/22#issuecomment-664054390), the problem has been solved!

Thanks @Tienisto
