### ISSUE TITLE
Error when creating release apk

### ISSUE THREAD

**Issue by Deuque** [magnatronus/flutter-devicelocale#25]
i get the following error when trying to create release apk, from the DeviceLocalePlugin.java

C:\Users\HP\Desktop\CubicLabs\email_scrapper>flutter build apk
Running "flutter pub get" in email_scrapper...                      0.7s
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloads_path_provider:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\HP\.gradle\caches\transforms-2\files-2.1\7bcac1eefa2bb1f0e62878f30cab7d5d\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSet
tings not found.

     C:\Users\HP\.gradle\caches\transforms-2\files-2.1\7bcac1eefa2bb1f0e62878f30cab7d5d\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not fou
nd.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      61.9s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin device_info...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    3.0s
√ Built build\app\outputs\repo.
Building plugin devicelocale...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    3.6s

C:\programs\flutter\.pub-cache\hosted\pub.dartlang.org\devicelocale-0.3.2\android\src\main\java\com\example\devicelocale\DevicelocalePlugin.java:3: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
C:\programs\flutter\.pub-cache\hosted\pub.dartlang.org\devicelocale-0.3.2\android\src\main\java\com\example\devicelocale\DevicelocalePlugin.java:4: error: package androidx.core.os does n
ot exist
import androidx.core.os.LocaleListCompat;
                       ^
C:\programs\flutter\.pub-cache\hosted\pub.dartlang.org\devicelocale-0.3.2\android\src\main\java\com\example\devicelocale\DevicelocalePlugin.java:54: error: cannot find symbol
  public void onMethodCall(MethodCall call, @NonNull Result result) {
                                             ^
  symbol:   class NonNull
  location: class DevicelocalePlugin
C:\programs\flutter\.pub-cache\hosted\pub.dartlang.org\devicelocale-0.3.2\android\src\main\java\com\example\devicelocale\DevicelocalePlugin.java:76: error: cannot find symbol
      LocaleListCompat list = LocaleListCompat.getAdjustedDefault();
      ^
  symbol:   class LocaleListCompat
  location: class DevicelocalePlugin
C:\programs\flutter\.pub-cache\hosted\pub.dartlang.org\devicelocale-0.3.2\android\src\main\java\com\example\devicelocale\DevicelocalePlugin.java:76: error: cannot find symbol
      LocaleListCompat list = LocaleListCompat.getAdjustedDefault();
                              ^
  symbol:   variable LocaleListCompat
  location: class DevicelocalePlugin
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

The plugin devicelocale could not be built due to the issue above.

**Comment by fellow7000** [comment]
Have same issue w. 0.3.3 trying to build release apk. app can be built. Any ideas how to fix?..

**Comment by magnatronus** [comment]
They may be a number of factors that give you these errors, including another plugin. 

With the trace that @Deuque  provided it lists

_**Running "flutter pub get" in email_scrapper... 0.7s**_

also 

`C:\Users\HP\.gradle\caches\transforms-2\files-2.1\7bcac1eefa2bb1f0e62878f30cab7d5d\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not fou`

I would look at these errors first.

Also Have you tried compiling with a vanilla Flutter project  and just the plugin (i.e. the example project)?

If it does not work with the example( which it does for me) then I can look into it further but would need to know stuff like:

What Android version of the SDK are you using
Are there any other plugins in the project
What version of Flutter is being used

**Comment by dzhaparoff** [comment]
Same issue here

**Comment by magnatronus** [comment]
@dzhaparoff  same reply as to @Deuque does it work OK with the standard example code(ie. with no other plugins). If not if you let me have the details of target Android, Flutter version (Flutter Channel) etc. I can look into it further.

**Comment by hungrymissilepod** [comment]
Just found a fix for my issue with this, not sure if it will help others:

My issue turns out to come from the keyboard_visibility plugin having compileSdkVersion set to 27 in it's build.grade. Setting this to 28 has fixed my issue.

I would recommend to create an new Flutter project, add the devicelocale plugin and make sure it can build a release version. Then add your plugins one at a time until the build fails. You should be able to work out which of your plugins if messing up the build.
