### ISSUE TITLE
Flutter Test - MissingPluginException(No implementation found for method currentLocale on channel uk.spiralarm.flutter/devicelocale)

### ISSUE THREAD

**Issue by biklas7** [magnatronus/flutter-devicelocale#3]
Got MissingPluginException(No implementation found for method currentLocale on channel uk.spiralarm.flutter/devicelocale) while running `flutter test`.

This might be a solution:
```
const MethodChannel('uk.spiralarm.flutter/devicelocale')
      .setMockMethodCallHandler((methodCall) async => 'en_GB');
```

**Comment by matthiaszarzecki** [comment]
I encountered the same issue! I could "solve" it by doing a `flutter clean` :)
