### ISSUE TITLE
Getting a "Deprecated API" warning

### ISSUE THREAD

**Issue by Dumdidoo** [magnatronus/flutter-devicelocale#33]
Hi,

I'm getting the following warning on compilation:

Note: C:\Users\BlaBla\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\devicelocale-0.4.1\android\src\main\java\com\example\devicelocale\DevicelocalePlugin.java uses or overrides a deprecated API.

Is this of concern?

Regards ~ Brian

**Comment by ibakhsh** [comment]
same here!

**Comment by magnatronus** [comment]
@ibakhsh  version 0.5.0 should stop this warning
