### ISSUE TITLE
getDeviceLocale() returns null for iPhone simulator

### ISSUE THREAD

**Issue by markbeij** [magnatronus/flutter-devicelocale#34]
In version 0.3.3 I got a locale back from the iPhone 12 Pro Max simulator
After upgrade to 0.4.1 I get null

**Comment by denes16** [comment]
same here!, any news on this? or other option to get the device locale?

**Comment by magnatronus** [comment]
@denes16  Do you get the issue if you test by running the example included with the plugin ? I have tried this using a newly created iPhone 12 Max sim (IOS 15.0) , Flutter 2.5.1 and plugin version 0.4.3 and it works OK.

**Comment by markbeij** [comment]
I can’t check this the upcoming period. Would be great if @magnatronus can check this. Maybe Apple fix something in the simulators

**Comment by magnatronus** [comment]
@markbeij  not sure what you mean by me check it ? - I just posted the latest comment - and have checked it.

**Comment by markbeij** [comment]
Oops I meant @denes16
