### ISSUE TITLE
Cannot build, compileSdkVersion 33

### ISSUE THREAD

**Issue by EDnny12** [magnatronus/flutter-devicelocale#46]
lambda expressions are not supported in -source 7
    Runnable myRunnable = () -> {
                             ^
  (use -source 8 or higher to enable lambda expressions)
1 error

**Comment by vanlooverenkoen** [comment]
Duplicate of #47

**Comment by magnatronus** [comment]
Closing - Duplicate of https://github.com/magnatronus/flutter-devicelocale/issues/47
