### ISSUE TITLE
Cannot build with CompileSdkVersion 33

### ISSUE THREAD

**Issue by EDnny12** [magnatronus/flutter-devicelocale#47]
lambda expressions are not supported in -source 7
    Runnable myRunnable = () -> {
                             ^
  (use -source 8 or higher to enable lambda expressions)
1 error

**Comment by magnatronus** [comment]
@EDnny12  I will need more context to the problem you are having as I do not understand the issue.

For example, Your flutter Doctor output, what device you are trying to use, the target OS and version etc. 

It may be that @vanlooverenkoen  would need to look into this

**Comment by vanlooverenkoen** [comment]
I will create a new pr

**Comment by SylvainFlattet** [comment]
> I will create a new pr

Great, got the exact same error since yesterday. And absolutely no detail on others forums.
Could you give us a slight explanation ? I can get curious sometimes :)

Thx!

**Comment by vanlooverenkoen** [comment]
I am working on it right now. @SylvainFlattet I will add you as well.

**Comment by magnatronus** [comment]
A lot of chatter about this from various people to do with flutter plug-ins - just do a search on

**flutter lambda expressions are not supported in -source 7**

most seem to solve the issue modifying the android/build.gradle file and adding/updating  the **compileOptions**, see snippet below.

```
android {

     compileOptions {
       sourceCompatibility JavaVersion.VERSION_1_8
       targetCompatibility JavaVersion.VERSION_1_8
     }

```

**Comment by vanlooverenkoen** [comment]
Ah alright, I thought specifically for this plugin. 
Yes, all our projects have been using 1.8 for a very long time. So did think of java 7 (which was released in 2011 🙈)

**Comment by SylvainFlattet** [comment]
Here's my flutter doctor -v

[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale fr-FR)
    • Flutter version 3.0.4 at /Users/sflattet/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (6 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sflattet/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114
    ! Error: ixn is not connected. Xcode will continue when ixn is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by SylvainFlattet** [comment]
@magnatronus 

Is used  this 
  devicelocale:
    git:
      url: https://github.com/magnatronus/flutter-devicelocale.git
      ref: aeac2ac808de8e1016ab9395acad308196e45c3c

And build is now ok. Thanks !!

But, switching to non-lambda function, is fine, but seems to me that I should fix the issue in the project settings. No?
Just for my knowledge, I tried to force java 8, with the same compileOption and kotlinOption before :
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

but those settings did not fix the issue : error: lambda expressions are not supported in -source 7
Does someone known how to _(use -source 8 or higher to enable lambda expressions)_ ??

**Comment by magnatronus** [comment]
@SylvainFlattet  OK I will merge the PR and rebuild

**Comment by vanlooverenkoen** [comment]
@SylvainFlattet thanks for testing!!

**Comment by magnatronus** [comment]
version 0.5.4 has now been uploaded
