### ISSUE TITLE
This package support per-app language for iOS?

### ISSUE THREAD

**Issue by deandreamatias-worldline** [magnatronus/flutter-devicelocale#55]
I didn't found an implementation of [per-app language](https://developer.apple.com/news/?id=u2cfuj88) iOS for Flutter on any package. I have a doubt if this package support it

**Comment by SteveCMAC** [comment]
It is only designed to help with identifying the locales that are set up on a device. It is down to the developer to implement the actual language support/switching, but there are packages that will assist with this type of app based language switching.

**Comment by deandreamatias-worldline** [comment]
Ok perfect. But in the case that implement [per-app language](https://developer.apple.com/news/?id=u2cfuj88) on iOS, this package handle this language change correctly? Or is the same that the global language change?

**Comment by magnatronus** [comment]
As mentioned above,  It is only designed to check the languages that are set on the device, which it should do correctly on the supported platforms. 

It does not detect in app languages changes, just the device locales set up and the default one, so if you change the default language you should be able to read the new default language using the plugin.

But it would not do this automatically you would need to re-query the data. It may be possible to add the detection within the plugin (as an upgrade), or probably better to create a new plugin  for the functionality you are after that will detect these changes and trigger something else in the app.

**Comment by deandreamatias-worldline** [comment]
I understand.
My question is specifically about if the methods of this package:
```dart
List languages = await Devicelocale.preferredLanguages;
String locale = await Devicelocale.currentLocale;
```
will get correctly if is a global language or a per-app language
