### ISSUE TITLE
Support for WASM on web

### ISSUE THREAD

**Issue by dorklein** [magnatronus/flutter-devicelocale#62]
Currently when trying to compile to web with --wasm you get:
```bash
../../../.pub-cache/hosted/pub.dev/devicelocale-0.7.1/lib/devicelocale_web.dart:6:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html show window;
```

As noted on the [official docs](https://docs.flutter.dev/platform-integration/web/wasm)

> **Dart's next-gen web interop is now stable!**
> Migrate your packages to [package:web](https://pub.dev/packages/web) and [dart:js_interop](https://api.dart.dev/stable/dart-js_interop) to make them compatible with Wasm. Read the [Requires JS-interop](https://docs.flutter.dev/platform-integration/web/wasm#js-interop-wasm) section to learn more.

**Comment by SteveCMAC** [comment]
done

**Comment by magnatronus** [comment]
merged
