### ISSUE TITLE
Set wanted locale for a emulator

### ISSUE THREAD

**Issue by joeblew99** [magnatronus/flutter-devicelocale#7]
Anyone know how to tell android or iOS emulator what locale you want it to run in ?

Will make testing easier ...

**Comment by magnatronus** [comment]
The same way as you would for a real device. Just use (in iOS) the settings on the emulator to set the language and region.

**Comment by joeblew99** [comment]
Yeah i know that.

i want to set it from the command line for automated real device testing :)
