### ISSUE TITLE
Support for Flutter Web not working

### ISSUE THREAD

**Issue by genovoxx** [magnatronus/flutter-devicelocale#9]
Hi there,
on pub.dev, devicelocale 0.2.1 is shown as flutter web enabled.
However, when I try to get the locale of a flutter web app, the package fails to return the device locale. What can I do to get it working?

Best, Christian

**Comment by creativecreatorormaybenot** [comment]
That is because this plugin does not support the `flutter.plugin.platforms` map in `pubspec.yaml`.

Pub just shows that it works on web because it does not know better. This plugin has no web implementation.

**Comment by nstrelow** [comment]
Any alternatives for this plugin?

**Comment by genovoxx** [comment]
Hi Nils, use 

package:universal_html/html.dart as UH

UH.window.navigator.language

Works well for me.

**Comment by nstrelow** [comment]
```
import dart:ui as ui;
ui.window.locale; 
```

Also works for me

**Comment by magnatronus** [comment]
closing issue as pub.dev now correctly reflects the platform availability

**Comment by aytunch** [comment]
@magnatronus pub.dev still shows web as supported. Is this the case? because in the example project there is no web folder. thanks.

**Comment by magnatronus** [comment]
@aytunch  it is, the example will run on web as well on on a mobile device. You just need to enable the example project for web if you want to test it. Select Chrome(web) as the device to use and you will be asked if you want to enable web support for the example project.

Apologies I will do this step in the next update.
